apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resmon
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resmon
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: resmon
  apiGroup: rbac.authorization.k8s.io
